export const userTypes = {
    SET_EMAIL_LOGIN: 'SET_EMAIL_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    FORGOT_EMAIL_FAIL: 'FORGOT_EMAIL_FAIL',
    FORGOT_EMAIL_SUCCESS: 'FORGOT_EMAIL_SUCCESS',
    SET_EMAIL_FORGOTPASSWORD: 'SET_EMAIL_FORGOTPASSWORD',
    RESET_FORGOT_PASSWORD: 'RESET_FORGOT_PASSWORD',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAIL: 'VERIFY_OTP_FAIL',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',
    RESET_IS_LOGIN: 'RESET_IS_LOGIN'
}

export const homeTypes = {
    SET_CATEGORY_BOOK: 'SET_CATEGORY_BOOK',

    SET_PUBLISHSER: "SET_PUBLISHSER",

    SET_PAGE: 'SET_PAGE',
    SET_BOOK: 'SET_BOOK',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
}

export const productTypes = {
    SET_PRODUCT_DETAIL: 'SET_PRODUCT_DETAIL',
    SET_NAME_CATEGORY: 'SET_NAME_CATEGORY',
    SET_NAME_PUBLICSHER: 'SET_NAME_PUBLICSHER'
}
export const profileTypes = {
    SET_AUTH_LOGIN_SUCCESS: 'SET_AUTH_LOGIN_SUCCESS',
    SET_AUTH_LOGIN_FAIL: 'SET_AUTH_LOGIN_FAIL',

    UPDATE_INFOR_USER_SUCCESS: 'UPDATE_INFOR_USER_SUCCESS',
    UPDATE_INFOR_USER_FAIL: 'UPDATE_INFOR_USER_FAIL',
    RESET_PROFILE: 'RESET_PROFILE'
}